#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ];then
    echo
    echo "usage:   ./dump [hostname] [output directory]"
    echo
    echo "example: ./dump dvrpi dvrpi_channels"
    echo
else
    mkdir -p $2 || /bin/true
    node main.js -u "http://$1:9981" -o "$2"
fi
